#!/bin/bash

if [[ -z "${GITHUB_TOKEN}" ]]; then
    echo "GITHUB_TOKEN must be set to use this script"
    exit 1
fi

FILE="https://api.github.com/repos/nexcess/puppet-config/contents/hieradata/common.d/network.yaml"

pushd vars 1>/dev/null
curl --header "Authorization: token $GITHUB_TOKEN" \
     --header 'Accept: application/vnd.github.v3.raw' \
     --remote-name \
     --location $FILE 2>/dev/null

if [ $? -ne 0 ]; then
    echo "!! network.yml file NOT DOWNLOADED !!"
    exit 1
fi

perl -pi -e 's/nexcess_firewall::cidr_blocks/nexcess_firewall_cidr_blocks/g' network.yaml

popd 1>/dev/null
